version: '3.8'

services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: VLSymZgffbnWWxEvJQgnXBgEPXWvJGSh
      POSTGRES_DB: library_db
    ports:
      - "37380:5432"
